# Generated by Django 5.0.1 on 2024-02-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='published_date',
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
