# Generated by Django 5.0.1 on 2024-02-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_project_text_remove_project_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
