# Generated by Django 5.0.1 on 2024-02-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='githubUrl',
            field=models.CharField(default='a', max_length=200),
        ),
    ]
