# Generated by Django 5.0.1 on 2024-02-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_project_githuburl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='githubUrl',
            new_name='repo',
        ),
    ]
