# Generated by Django 5.0.1 on 2024-02-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_githuburl_project_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repo',
            field=models.CharField(max_length=200),
        ),
    ]
