# Generated by Django 5.0.1 on 2024-02-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_project_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='typee',
            field=models.TextField(choices=[('Application', 'Application'), ('Game', 'Game')], default='Application'),
        ),
    ]
