# Generated by Django 5.0.1 on 2024-02-14 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_typee_project_projecttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectType',
            new_name='project_type',
        ),
    ]
